src/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'PostController@index')->name('all_posts');
Route::get('/today', 'PostController@today')->name('today');

Route::get('/p/{post:uri}', 'PostController@show')->name('show_post');

Route::get('/s/{site:domain}', 'SiteController@index')->name('show.site.posts');

// User Space
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/new', 'PostController@create')->name('new');
    Route::post('/new', 'PostController@create_post')->name('create_post');
    Route::get('/p/{post:uri}/report', 'ReportController@create')->name('post_report');
    Route::post('/p/{post:uri}/report', 'ReportController@store')->name('create_post_report');

    Route::post('/p/{post:uri}/c', 'CommentController@commentPost')
        ->name('post.comment');

    Route::get('/p/{post:uri}/d', 'PostController@destroy')
        ->name('post.delete');

    Route::get('/p/{post:uri}/v/{reaction}', 'VoteController@votePost')
        ->where('reaction', '[0-1]')
        ->name('post.vote');
});


// Admin Space
Route::middleware(['auth', 'admin'])->name('admin.')->prefix('admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('home');
    Route::get('/users', 'AdminController@showUsers')->name('users');
    Route::get('/users/{user:id}/d', 'AdminController@deleteUser')->name('users.delete');
    Route::get('/users/{user:id}/a', 'AdminController@makeAdmin')->name('users.make_admin');

    Route::get('/posts', 'AdminController@showPosts')->name('posts');
    Route::get('/posts/{post:id}/d', 'PostController@destroy')->name('posts.delete');

    Route::name('reports.')->prefix('reports')->group(function () {
        Route::get('/all', 'AdminController@showAllReports')->name('all');

        Route::get('/{report}/d', 'AdminController@deleteReport')->name('delete');

        Route::get('/post', 'AdminController@showPostReports')->name('post');
        Route::get('/post/{post:uri}', 'AdminController@showPostReports')->name('post_id');

    });

    Route::get('/comments', 'AdminController@showComments')->name('comments');
    Route::get('/comments/{comment}', 'AdminController@deleteComment')->name('comments.delete');

});

Auth::routes();

src/resources/views/admin/comments.blade.php
@extends('admin.layout')
@section('content-admin')
    <div class="row  mb-4 m-0 px-3 justify-content-center">
        <div class="card m-1 border-danger">
            <div class="card-header">تعداد نظرات</div>
            <div class="card-body pr-1 pl-1 p-0 justify-content-center row">
                <span class="text-danger pl-1 pr-1">{{num_to_fa($comments_count)}}</span>
            </div>
        </div>
    </div>

    @if($last_page !=1 )
        <div class="row justify-content-center">
            <nav>
                <ul class="pagination mb-4 m-0 p-0">
                    <li class="page-item">
                        <a class="page-link" href="?page={{($current_page > 1)? $current_page-1:'1'}}"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    @for($i=1 ; $i <= $last_page ; $i++)
                        <li class="page-item {{($i == $current_page)? 'active':''}}">
                            <a class="page-link" href="?page={{$i}}">{{num_to_fa($i)}}</a>
                        </li>
                    @endfor

                    <li class="page-item">
                        <a class="page-link" href="?page={{($current_page < $last_page)? $current_page+1:$last_page}}"
                           aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    @endif

    <div class="row justify-content-center">
        <div class="col-md-8">
            <ul class="list-group text-right">
                @foreach($comments as $index=>$comment)
                    <li class="list-group-item">
                        <div class="row post text-right mr-0 ml-0">
                            <div class="col-12 post-body">
                                <h2>
                                    <span class="text-secondary number">
                                        {{ num_to_fa($index + 1) }}
                                    </span>
                                    .
                                    {{$comment->body}}
                                </h2>
                                <h3 class="text-secondary">
                                    <a href="{{route('show_post',['post'=>$comment->commentable])}}">
                                        <span class="badge badge-dark ltr">
                                            {{'#'.$comment->commentable->uri}}
                                        </span>
                                    </a>
                                    |
                                    {{ num_to_fa(\Morilog\Jalali\Jalalian::forge($comment->created_at)->ago()) }}
                                    |
                                    <span>
                                        {{$comment->User->name}}
                                    </span>
                                    |
                                    <a href="{{route('admin.comments.delete',['comment'=>$comment])}}" class="text-danger">
                                        حذف نظر
                                    </a>
                                </h3>
                            </div>
                        </div>
                    </li>
                @endforeach
            </ul>
        </div>
    </div>
@endsection

src/resources/views/admin/home.blade.php
@extends('admin.layout')
@section('content-admin')
    <div class="row">
        <div class="col-12 text-center">
            <h3>شما به عنوان ادمین وارد شدید.</h3>
        </div>
    </div>
@endsection

src/resources/views/admin/layout.blade.php
@extends('layouts.app')
@section('content')

    <nav class="navbar navbar-light bg-primary justify-content-center mb-4" style="margin-top: -1.5rem">
        <a class="text-white pr-1 pl-1" href="{{ route('admin.users') }}">کاربران</a>
        <a class="text-white pr-1 pl-1" href="{{ route('admin.posts') }}">پست‌ها</a>
        <a class="text-white pr-1 pl-1" href="{{ route('admin.comments') }}">نظرات</a>
        <a class="text-white pr-1 pl-1" href="{{ route('admin.reports.all') }}">گزارشات</a>
    </nav>
    @yield('content-admin')
@endsection

src/resources/views/admin/posts.blade.php
@extends('admin.layout')
@section('content-admin')
    <div class="row  mb-4 m-0 px-3 justify-content-center">
        <div class="card m-1 border-success">
            <div class="card-header">تعداد پست‌ها</div>
            <div class="card-body pr-1 pl-1 p-0 justify-content-center row">
                <span class="text-danger pl-1 pr-1">{{num_to_fa($posts_count)}}</span>
            </div>
        </div>
        <div class="card m-1 border-dark">
            <div class="card-header">پاک شده‌ها</div>
            <div class="card-body pr-1 pl-1 p-0 justify-content-center row">
                <span class="text-danger pl-1 pr-1">{{num_to_fa($trashed_count)}}</span>
            </div>
        </div>
    </div>

    @if($last_page !=1 )
        <div class="row justify-content-center">
            <nav>
                <ul class="pagination mb-4 m-0 p-0">
                    <li class="page-item">
                        <a class="page-link" href="?page={{($current_page > 1)? $current_page-1:'1'}}"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    @for($i=1 ; $i <= $last_page ; $i++)
                        <li class="page-item {{($i == $current_page)? 'active':''}}">
                            <a class="page-link" href="?page={{$i}}">{{num_to_fa($i)}}</a>
                        </li>
                    @endfor

                    <li class="page-item">
                        <a class="page-link" href="?page={{($current_page < $last_page)? $current_page+1:$last_page}}"
                           aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    @endif

    <div class="row m-0 px-3 justify-content-center">
        @foreach($posts as $post)
            <div class="card m-1 {{ ($post->isTrashed())? 'border-dark': 'border-primary'}}"
                 style="min-width: 125px;">
                <div class="card-header text-center">

                    <a href="{{route('show_post',['post'=>$post])}}" class="text-center">
                        {{'#'.$post->uri}}
                    </a>
                    <br>
                    <span class="badge badge-secondary">{{num_to_fa($post->likes-$post->dislikes)}}</span>
                    <span class="badge badge-dark">{{num_to_fa($post->comments_count)}}</span>
                    <br>
                    <span class="badge badge-dark">{{$post->User->name}}</span>
                    <br>

                </div>

                @if(!$post->isTrashed())
                    <div class="card-body px-1 p-0 justify-content-center row">
                        <a href="{{route('admin.posts.delete',['post'=>$post])}}" class="text-danger pl-1 pr-1">حذف</a>
                        <a href="{{route('admin.reports.post_id', ['post'=>$post])}}" class="text-secondary pl-1 pr-1">گزارشات</a>
                    </div>
                @else
                    <div class="card-body px-1 p-0 bg-dark  text-center text-white justify-content-center">
                        <span>حذف شده</span>
                    </div>
                @endif

            </div>

        @endforeach

    </div>
@endsection

src/resources/views/admin/users.blade.php
@extends('admin.layout')
@section('content-admin')
    <div class="row  mb-4 m-0 px-3 justify-content-center">
        <div class="card m-1 border-success">
            <div class="card-header">ادمین‌ها</div>
            <div class="card-body pr-1 pl-1 p-0 justify-content-center row">
                <span class="text-danger pl-1 pr-1">{{num_to_fa($admins_count)}}</span>
            </div>
        </div>
        <div class="card m-1 border-primary">
            <div class="card-header">تعداد کل</div>
            <div class="card-body pr-1 pl-1 p-0 justify-content-center row">
                <span class="text-danger pl-1 pr-1">{{ num_to_fa($users_count) }}</span>
            </div>
        </div>

    </div>

    @if($last_page !=1 )
        <div class="row justify-content-center">
            <nav>
                <ul class="pagination mb-4 m-0 p-0">
                    <li class="page-item">
                        <a class="page-link" href="?page={{($current_page > 1)? $current_page-1:'1'}}"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    @for($i=1 ; $i <= $last_page ; $i++)
                        <li class="page-item {{($i == $current_page)? 'active':''}}">
                            <a class="page-link" href="?page={{$i}}">{{num_to_fa($i)}}</a>
                        </li>
                    @endfor

                    <li class="page-item">
                        <a class="page-link" href="?page={{($current_page < $last_page)? $current_page+1:$last_page}}"
                           aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    @endif

    <div class="row m-0 px-3 justify-content-center">
        @foreach($users as $user)
            <div class="card m-1 {{ ($user->role=='ADMIN')? 'border-success':'border-primary' }}"
                 style="min-width: 100px;">
                <div class="card-header text-center">
                    {{$user->name}}
                </div>
                <div class="card-body px-1 p-0 justify-content-center row">
                    <a href="{{route('admin.users.delete',['user'=>$user])}}" class="text-danger pl-1 pr-1">حذف</a>
{{--                    <a href="" class="text-secondary pl-1 pr-1">گزارشات</a>--}}
                    @if($user->role!='ADMIN')
                        <a href="{{route('admin.users.make_admin',['user'=>$user])}}"
                           class="text-dark pl-1 pr-1">ارتقا</a>
                    @endif

                </div>
            </div>

        @endforeach

    </div>


@endsection