src/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'PostController@index')->name('all_posts');
Route::get('/today', 'PostController@today')->name('today');

Route::get('/p/{post:uri}', 'PostController@show')->name('show_post');

Route::get('/s/{site:domain}', 'SiteController@index')->name('show.site.posts');

// User Space
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/new', 'PostController@create')->name('new');
    Route::post('/new', 'PostController@create_post')->name('create_post');
    Route::get('/p/{post:uri}/report', 'ReportController@create')->name('post_report');
    Route::post('/p/{post:uri}/report', 'ReportController@store')->name('create_post_report');

    Route::post('/p/{post:uri}/c', 'CommentController@commentPost')
        ->name('post.comment');

    Route::get('/p/{post:uri}/d', 'PostController@destroy')
        ->name('post.delete');

    Route::get('/p/{post:uri}/v/{reaction}', 'VoteController@votePost')
        ->where('reaction', '[0-1]')
        ->name('post.vote');
});


// Admin Space
Route::middleware(['auth', 'admin'])->name('admin.')->prefix('admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('home');
    Route::get('/users', 'AdminController@showUsers')->name('users');
    Route::get('/users/{user:id}/d', 'AdminController@deleteUser')->name('users.delete');
    Route::get('/users/{user:id}/a', 'AdminController@makeAdmin')->name('users.make_admin');

    Route::get('/posts', 'AdminController@showPosts')->name('posts');
    Route::get('/posts/{post:id}/d', 'PostController@destroy')->name('posts.delete');

    Route::name('reports.')->prefix('reports')->group(function () {
        Route::get('/all', 'AdminController@showAllReports')->name('all');

        Route::get('/{report}/d', 'AdminController@deleteReport')->name('delete');

        Route::get('/post', 'AdminController@showPostReports')->name('post');
        Route::get('/post/{post:uri}', 'AdminController@showPostReports')->name('post_id');

    });

    Route::get('/comments', 'AdminController@showComments')->name('comments');
    Route::get('/comments/{comment}', 'AdminController@deleteComment')->name('comments.delete');

});

Auth::routes();

src/app/Report.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Report extends Model
{
    use SoftDeletes;
    
    public static $reasons = ['ABUSE', 'SPAM', 'PORN', 'OTHER'];
    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function reportable()
    {
        return $this->morphTo();
    }
}

src/app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateReportRequest;
use App\Post;
use App\Report;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new Report for Post.
     *
     * @param Post $post
     * @return Factory|View
     */
    public function create(Post $post)
    {
        return view('posts.report', ['post' => $post]);
    }

    /**
     * Store a newly created Report in storage.
     *
     * @param Post $post
     * @param CreateReportRequest $request
     * @return Factory|View
     */
    public function store(Post $post, CreateReportRequest $request)
    {

        try {
            $post->reports()->create([
                'user_id' => Auth::user()->id,
                'reason' => $request->reason,
                'body' => $request->body
            ]);
            return view('posts.report_success');
        } catch (Exception $e) {
            return view('posts.report', ['post' => $post, 'error' => true]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param Report $report
     * @return Response
     */
    public function show(Report $report)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Report $report
     * @return Response
     */
    public function edit(Report $report)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Report $report
     * @return Response
     */
    public function update(Request $request, Report $report)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Report $report
     * @return Response
     */
    public function destroy(Report $report)
    {
        //
    }
}

src/resources/views/admin/report/all.blade.php
@extends('admin.layout')

@section('content-admin')
    <div class="row  mb-4 m-0 px-3 justify-content-center">
        <div class="card m-1 border-danger">
            <div class="card-header">تعداد کل ریپوت‌ها</div>
            <div class="card-body pr-1 pl-1 p-0 justify-content-center row">
                <span class="text-danger pl-1 pr-1">{{num_to_fa($all_reports_count)}}</span>
            </div>
        </div>

        <div class="card m-1 border-primary">
            <a href="{{route('admin.reports.post')}}">
                <div class="card-header text-dark">پست‌ها</div>
            </a>
            <div class="card-body pr-1 pl-1 p-0 justify-content-center row">
                <span class="text-danger pl-1 pr-1">{{num_to_fa($post_reports_count)}}</span>
            </div>
        </div>
        <div class="card m-1 border-dark">
            <div class="card-header">پاک شده‌ها</div>
            <div class="card-body pr-1 pl-1 p-0 justify-content-center row">
                <span class="text-danger pl-1 pr-1">{{num_to_fa($trashed_reports_count)}}</span>
            </div>
        </div>
    </div>
@endsection

src/resources/views/admin/report/post.blade.php
@extends('admin.layout')
@section('content-admin')
    <div class="row  mb-4 m-0 px-3 justify-content-center">
        <div class="card m-1 border-danger">
            <div class="card-header">تعداد گزارش‌ها</div>
            <div class="card-body pr-1 pl-1 p-0 justify-content-center row">
                <span class="text-danger pl-1 pr-1">{{num_to_fa($reports_count)}}</span>
            </div>
        </div>
    </div>

    @if($last_page !=1 )
        <div class="row justify-content-center">
            <nav>
                <ul class="pagination mb-4 m-0 p-0">
                    <li class="page-item">
                        <a class="page-link" href="?page={{($current_page > 1)? $current_page-1:'1'}}"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    @for($i=1 ; $i <= $last_page ; $i++)
                        <li class="page-item {{($i == $current_page)? 'active':''}}">
                            <a class="page-link" href="?page={{$i}}">{{num_to_fa($i)}}</a>
                        </li>
                    @endfor

                    <li class="page-item">
                        <a class="page-link" href="?page={{($current_page < $last_page)? $current_page+1:$last_page}}"
                           aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    @endif

    <div class="row justify-content-center">
        <div class="col-md-8">
            <ul class="list-group text-right">
                @foreach($reports as $index=>$report)
                    <li class="list-group-item">
                        <div class="row post text-right mr-0 ml-0">
                            <div class="col-12 post-body">
                                <h2>
                                    <span class="text-secondary number">
                                        {{ num_to_fa($index + 1) }}
                                    </span>
                                    .
                                    {{$report->body}}
                                </h2>
                                <h3 class="text-secondary">
                                    <a href="{{route('show_post',['post'=>$report->reportable])}}">
                                        <span class="badge badge-dark ltr">
                                            {{'#'.$report->reportable->uri}}
                                        </span>
                                    </a>
                                    <span class="badge badge-danger ltr">
                                            {{'#'.$report->reason}}
                                    </span>
                                    |
                                    {{ num_to_fa(\Morilog\Jalali\Jalalian::forge($report->created_at)->ago()) }}
                                    |
                                    <span>
                                        {{$report->User->name}}
                                    </span>
                                    |
                                    <a href="{{route('post.delete',['post'=>$report->reportable])}}"
                                       class="text-danger">
                                        حذف پست
                                    </a>
                                    |
                                    <a href="{{route('admin.reports.delete',['report'=>$report])}}" class="text-dark">
                                        حذف گزارش
                                    </a>
                                </h3>
                            </div>
                        </div>
                    </li>
                @endforeach
            </ul>
        </div>
    </div>
@endsection

src/resources/views/admin/report/site.blade.php
@extends('admin.layout')

@section('content-admin')
@endsection